//! Environment configuration.
//!
//! Every name and default is carried over from the Python service's
//! `backend/app/core/config.py`. The Fly app's secrets are already set
//! against these names, so renaming one silently reverts it to a default
//! at the next deploy.

use std::env;

#[derive(Debug, Clone)]
pub struct Config {
    pub database_url: String,
    /// Port this process listens on.
    pub port: u16,
    /// Directory holding the built SPA (`frontend/dist` copied to
    /// `/app/static` by the Dockerfile).
    pub static_dir: String,
    /// Install and MCP-setup scripts, served verbatim.
    pub scripts_dir: String,
    /// Segments held per camera before the oldest are dropped. One
    /// second of video each, so the default is a minute of history.
    pub segment_cache_max_per_camera: usize,
    /// Ceiling on the sum of every camera's cache. The per-camera cap
    /// alone bounds nothing when five hundred cameras are live.
    pub segment_cache_max_total_bytes: i64,
    /// Largest single pushed segment, checked against Content-Length
    /// before any bytes are read.
    pub segment_push_max_bytes: usize,
    /// Largest pushed playlist, same check.
    pub playlist_push_max_bytes: usize,
    /// Playlist pushes between opportunistic cache sweeps.
    pub cleanup_interval: u64,
    /// The CameraNode build below which a node is refused outright.
    pub min_supported_node_version: String,
    /// The newest CameraNode release, as a fallback for when the
    /// GitHub cache is cold — a first boot, or a sustained outage.
    pub latest_node_version: String,
    /// The shared, multi-tenant key SourceBox's own Sentinel agent
    /// presents. Unset on a self-hosted install — which must NOT
    /// disable the per-org scoped keys, since that deployment is
    /// exactly the one that issues them.
    pub sentinel_agent_key: Option<String>,
    /// `SENTINEL_AGENT_MCP_KEY` — the agent's bearer for the tool
    /// surface, distinct from the run-queue key above on the
    /// first-party deployment.
    pub sentinel_agent_mcp_key: Option<String>,
    /// The self-hosted Sentinel licence key. Absent means unlicensed,
    /// which is a different refusal from an ineligible plan.
    pub sentinel_license_key: Option<String>,
    /// `SENTINEL_LICENSE_SERVICE_URL` — the sibling service the
    /// check-in loop talks to. Only the READ half of the licence
    /// contract existed in the port until the loops slice; this is what
    /// the write half posts to.
    pub sentinel_license_service_url: String,
    /// `SENTINEL_SYNC_SERVICE_URL` — the mirror's destination.
    pub sentinel_sync_service_url: String,
    /// Fleet-wide kill switch for agent dispatch.
    pub sentinel_dispatch_enabled: bool,
    /// Fleet-wide monthly run ceiling; 0 disables the ceiling.
    pub sentinel_global_monthly_run_cap: i64,
    /// Where to nudge the agent after queueing a run.
    pub sentinel_agent_webhook_url: Option<String>,
    /// Svix signing secret for Resend's webhooks (`whsec_...`). Without
    /// it every delivery is refused: an unverified bounce could
    /// suppress any address.
    pub resend_webhook_secret: Option<String>,
    pub clerk_webhook_secret: Option<String>,

    // --- Clerk ---------------------------------------------------------
    pub clerk_secret_key: String,
    /// Clerk Backend API base, including `/v1`. Overridable so the plan
    /// harness can point both stacks at a fake.
    pub clerk_api_url: String,
    pub clerk_publishable_key: String,
    /// Resolved from the publishable key; see `auth::issuer_from_publishable_key`.
    pub clerk_issuer: Option<String>,

    // --- local (self-hosted) auth --------------------------------------
    /// HS256 signing key for local session tokens.
    pub app_secret_key: String,
    pub local_org_id: String,
    pub local_admin_email: String,
    pub local_admin_username: String,
    /// Argon2 PHC string. Generated by
    /// `backend/scripts/hash_local_admin_password.py`.
    pub local_admin_password_hash: String,
    pub auth_provider: String,
    /// Shared storage for rate-limit counters.
    pub redis_url: String,
    /// The operator's platform-wide email kill switch. Defaults off, so
    /// a deployment that never sets it sends nothing.
    pub email_enabled: bool,
    pub resend_api_key: String,
    /// `resend.api_url` — the SDK reads it from the environment, which
    /// is what lets a fake Resend sit in front of BOTH tiers. Clerk's
    /// SDK has no equivalent, and that asymmetry is why the webhook's
    /// member-limit call is untestable and this is not.
    pub resend_api_url: String,
    pub email_from_address: String,
    pub email_from_name: String,
    pub email_worker_interval_seconds: u64,
    /// `OFFLINE_SWEEP_INTERVAL_SECONDS`. The only one of the loop
    /// cadences Python takes from the environment — the log cleanup's
    /// 24 hours and the 90-second heartbeat threshold are both
    /// hard-coded there.
    pub offline_sweep_interval_seconds: u64,
    /// The other three sweeps Python reads from the environment too.
    /// Tunable "down for ops or up for quieter environments", as its own
    /// comment says — and the differential is the quietest environment
    /// there is: a five-minute reaper firing mid-case in one tier and
    /// not the other is a side-effect difference with no code behind it.
    pub disk_check_interval_seconds: u64,
    pub motion_digest_interval_seconds: u64,
    pub sentinel_reaper_interval_seconds: u64,
    pub email_worker_batch_size: i64,
    pub email_max_attempts: i64,

    /// Checked against a Clerk token's `azp` claim — the Python service
    /// passes it to the SDK as `authorized_parties`.
    pub frontend_url: String,
    /// Comma-separated extra CORS origins.
    pub cors_allowed_origins: String,
}

impl Config {
    /// `AUTH_PROVIDER=local`. Anything else, including a typo, falls
    /// through to Clerk — the safe default, and the exact complement the
    /// Python config documents.
    pub fn is_local_auth(&self) -> bool {
        self.auth_provider == "local"
    }

    /// All three of the local-auth secrets are set.
    ///
    /// The login and refresh routes answer 503 when this is false,
    /// rather than rejecting every password as wrong — an operator who
    /// forgot a secret needs to see a configuration problem.
    /// `is_email_configured` — the wiring, not the operator switch.
    ///
    /// `EMAIL_ENABLED` is a deliberate "off"; this is "misconfigured",
    /// and the worker treats them differently: the first is a skipped
    /// send that still clears the row, the second is a permanent
    /// failure that retrying cannot fix.
    pub fn is_email_configured(&self) -> bool {
        !self.resend_api_key.is_empty() && !self.email_from_address.is_empty()
    }

    pub fn is_local_auth_configured(&self) -> bool {
        !self.app_secret_key.is_empty()
            && !self.local_admin_username.is_empty()
            && !self.local_admin_password_hash.is_empty()
    }

    pub fn is_clerk_configured(&self) -> bool {
        !self.clerk_secret_key.is_empty() && !self.clerk_publishable_key.is_empty()
    }
}

fn var_or(key: &str, default: &str) -> String {
    env::var(key).unwrap_or_else(|_| default.to_string())
}

impl Config {
    pub fn from_env() -> Self {
        let clerk_publishable_key = var_or("CLERK_PUBLISHABLE_KEY", "");
        let clerk_api_url = var_or("CLERK_API_URL", "https://api.clerk.com/v1");
        Self {
            database_url: normalize_database_url(&var_or(
                "DATABASE_URL",
                // The Python tier's default, and for the same reason: an
                // install that configures nothing gets a file beside the
                // binary rather than a connection refused.
                "sqlite:///./sentinel.db",
            )),
            port: var_or("PORT", "8000").parse().unwrap_or(8000),
            static_dir: var_or("STATIC_DIR", "/app/static"),
            scripts_dir: var_or("SCRIPTS_DIR", "/app/scripts"),
            segment_cache_max_per_camera: var_or("SEGMENT_CACHE_MAX_PER_CAMERA", "60")
                .parse()
                .unwrap_or(60),
            segment_cache_max_total_bytes: var_or(
                "SEGMENT_CACHE_MAX_TOTAL_BYTES",
                &(384 * 1024 * 1024).to_string(),
            )
            .parse()
            .unwrap_or(384 * 1024 * 1024),
            segment_push_max_bytes: var_or(
                "SEGMENT_PUSH_MAX_BYTES",
                &(2 * 1024 * 1024).to_string(),
            )
            .parse()
            .unwrap_or(2 * 1024 * 1024),
            playlist_push_max_bytes: var_or("PLAYLIST_PUSH_MAX_BYTES", &(64 * 1024).to_string())
                .parse()
                .unwrap_or(64 * 1024),
            cleanup_interval: var_or("CLEANUP_INTERVAL", "20").parse().unwrap_or(20),
            min_supported_node_version: var_or("MIN_SUPPORTED_NODE_VERSION", "0.1.0"),
            latest_node_version: var_or("LATEST_NODE_VERSION", "0.1.77"),
            sentinel_agent_key: std::env::var("SENTINEL_AGENT_KEY")
                .ok()
                .filter(|v| !v.is_empty()),
            sentinel_agent_mcp_key: std::env::var("SENTINEL_AGENT_MCP_KEY")
                .ok()
                .filter(|v| !v.is_empty()),
            sentinel_license_key: std::env::var("SENTINEL_LICENSE_KEY")
                .ok()
                .filter(|v| !v.is_empty()),
            sentinel_license_service_url: var_or("SENTINEL_LICENSE_SERVICE_URL", ""),
            sentinel_sync_service_url: var_or("SENTINEL_SYNC_SERVICE_URL", ""),
            // Python reads this as `.lower() == "true"`, so anything
            // else — including "1" — is false.
            sentinel_dispatch_enabled: var_or("SENTINEL_DISPATCH_ENABLED", "true").to_lowercase()
                == "true",
            sentinel_global_monthly_run_cap: var_or("SENTINEL_GLOBAL_MONTHLY_RUN_CAP", "0")
                .parse()
                .unwrap_or(0),
            resend_webhook_secret: std::env::var("RESEND_WEBHOOK_SECRET")
                .ok()
                .filter(|v| !v.is_empty()),
            clerk_webhook_secret: std::env::var("CLERK_WEBHOOK_SECRET")
                .ok()
                .filter(|v| !v.is_empty()),
            sentinel_agent_webhook_url: std::env::var("SENTINEL_AGENT_WEBHOOK_URL")
                .ok()
                .filter(|v| !v.is_empty()),
            clerk_issuer: crate::auth::issuer_from_publishable_key(&clerk_publishable_key),
            clerk_secret_key: var_or("CLERK_SECRET_KEY", ""),
            clerk_publishable_key,
            clerk_api_url,
            app_secret_key: var_or("APP_SECRET_KEY", ""),
            // "self-host", not "local" — this string is the org_id every
            // row in a self-hosted install is scoped by, so a different
            // default here would make the Rust tier read and write a
            // different tenant than the Python one.
            local_org_id: var_or("LOCAL_ORG_ID", "self-host"),
            local_admin_email: var_or("LOCAL_ADMIN_EMAIL", ""),
            local_admin_username: var_or("LOCAL_ADMIN_USERNAME", ""),
            local_admin_password_hash: var_or("LOCAL_ADMIN_PASSWORD_HASH", ""),
            auth_provider: var_or("AUTH_PROVIDER", "clerk"),
            redis_url: var_or("REDIS_URL", ""),
            email_enabled: var_or("EMAIL_ENABLED", "false").to_lowercase() == "true",
            resend_api_key: var_or("RESEND_API_KEY", ""),
            resend_api_url: var_or("RESEND_API_URL", "https://api.resend.com"),
            email_from_address: var_or("EMAIL_FROM_ADDRESS", "notifications@sentinel-command.com"),
            email_from_name: var_or("EMAIL_FROM_NAME", "Sentinel by SourceBox"),
            email_worker_interval_seconds: var_or("EMAIL_WORKER_INTERVAL_SECONDS", "5")
                .parse()
                .unwrap_or(5),
            offline_sweep_interval_seconds: var_or("OFFLINE_SWEEP_INTERVAL_SECONDS", "30")
                .parse()
                .unwrap_or(30),
            disk_check_interval_seconds: var_or("DISK_CHECK_INTERVAL_SECONDS", "300")
                .parse()
                .unwrap_or(300),
            motion_digest_interval_seconds: var_or("MOTION_DIGEST_INTERVAL_SECONDS", "60")
                .parse()
                .unwrap_or(60),
            sentinel_reaper_interval_seconds: var_or("SENTINEL_REAPER_INTERVAL_SECONDS", "300")
                .parse()
                .unwrap_or(300),
            email_worker_batch_size: var_or("EMAIL_WORKER_BATCH_SIZE", "20")
                .parse()
                .unwrap_or(20),
            email_max_attempts: var_or("EMAIL_MAX_ATTEMPTS", "3").parse().unwrap_or(3),
            frontend_url: var_or("FRONTEND_URL", "http://localhost:5173"),
            cors_allowed_origins: var_or(
                "CORS_ALLOWED_ORIGINS",
                "https://app.sentinel-command.com",
            ),
        }
    }
}

/// Why this build cannot open `url`, if it cannot.
///
/// One backend is compiled into each binary (`db.rs`), so the scheme is
/// checked by hand before the pool is built. Left to sqlx, a SQLite URL
/// handed to the PostgreSQL build is ten seconds of acquire timeout and
/// then "pool timed out while waiting for an open connection" — which
/// reads like a network fault, and sends the reader to check a database
/// that was never going to be contacted.
///
/// `main` tries the sibling binary first (`dispatch_to_matching_build`);
/// this is the sentence for when there is none.
pub fn unsupported_database_url(url: &str) -> Option<String> {
    use crate::db::{url_kind, UrlKind, BACKEND_NAME, SQLITE};
    let asked = match url_kind(url) {
        UrlKind::Postgres if !SQLITE => return None,
        UrlKind::Sqlite if SQLITE => return None,
        UrlKind::Postgres => "PostgreSQL",
        UrlKind::Sqlite => "SQLite",
        UrlKind::Other => {
            return Some(format!(
                "DATABASE_URL is {url:?}, which is neither a postgresql:// nor a \
                 sqlite:// URL. Command Center runs on PostgreSQL or on a SQLite \
                 file — for example sqlite:///./sentinel.db."
            ));
        }
    };
    let other_binary = crate::db::sibling_binary_name(&crate::db::own_binary_name());
    Some(format!(
        "DATABASE_URL is {url:?}, which asks for {asked}, and this binary is the \
         {BACKEND_NAME} build. The database driver is chosen when the binary is \
         compiled: run `{other_binary}` (it ships beside this one in the image), \
         or build it with `cargo build --release{}`.",
        if SQLITE { "" } else { " --features sqlite" }
    ))
}

/// Strip SQLAlchemy's `+driver` from a URL scheme.
///
/// The Fly secret holds `postgresql+psycopg://…`, which sqlx does not
/// understand. Normalising here means the secret does not have to be
/// rewritten during a migration that is already changing the runtime —
/// and it means both stacks can read the same variable while they run
/// side by side.
pub fn normalize_database_url(url: &str) -> String {
    match url.split_once("://") {
        Some((scheme, rest)) => match scheme.split_once('+') {
            Some((base, _driver)) => format!("{base}://{rest}"),
            None => url.to_string(),
        },
        None => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn config_with(auth_provider: &str, secret: &str, publishable: &str) -> Config {
        Config {
            database_url: String::new(),
            port: 8000,
            static_dir: String::new(),
            scripts_dir: String::new(),
            segment_cache_max_per_camera: 60,
            segment_cache_max_total_bytes: 384 * 1024 * 1024,
            segment_push_max_bytes: 2 * 1024 * 1024,
            playlist_push_max_bytes: 64 * 1024,
            cleanup_interval: 20,
            min_supported_node_version: "0.1.0".into(),
            latest_node_version: "0.1.77".into(),
            sentinel_agent_key: None,
            sentinel_agent_mcp_key: None,
            clerk_webhook_secret: None,
            sentinel_license_key: None,
            sentinel_license_service_url: String::new(),
            sentinel_sync_service_url: String::new(),
            sentinel_dispatch_enabled: true,
            sentinel_global_monthly_run_cap: 0,
            sentinel_agent_webhook_url: None,
            resend_webhook_secret: None,
            clerk_secret_key: secret.into(),
            clerk_publishable_key: publishable.into(),
            clerk_api_url: String::new(),
            clerk_issuer: None,
            app_secret_key: String::new(),
            local_org_id: "self-host".into(),
            local_admin_email: String::new(),
            local_admin_username: String::new(),
            local_admin_password_hash: String::new(),
            auth_provider: auth_provider.into(),
            redis_url: String::new(),
            email_enabled: false,
            resend_api_key: String::new(),
            resend_api_url: "https://api.resend.com".into(),
            email_from_address: String::new(),
            email_from_name: String::new(),
            email_worker_interval_seconds: 5,
            offline_sweep_interval_seconds: 30,
            disk_check_interval_seconds: 300,
            motion_digest_interval_seconds: 60,
            sentinel_reaper_interval_seconds: 300,
            email_worker_batch_size: 20,
            email_max_attempts: 3,
            frontend_url: String::new(),
            cors_allowed_origins: String::new(),
        }
    }

    #[test]
    fn anything_but_local_means_clerk() {
        // The Python config documents this as the safe default: a typo
        // in AUTH_PROVIDER must not silently disable authentication.
        assert!(config_with("local", "", "").is_local_auth());
        for provider in ["clerk", "", "Local", "locl", "none"] {
            assert!(
                !config_with(provider, "", "").is_local_auth(),
                "{provider:?} should not select local auth"
            );
        }
    }

    #[test]
    fn clerk_needs_both_keys_to_count_as_configured() {
        assert!(config_with("clerk", "sk", "pk").is_clerk_configured());
        assert!(!config_with("clerk", "sk", "").is_clerk_configured());
        assert!(!config_with("clerk", "", "pk").is_clerk_configured());
        assert!(!config_with("clerk", "", "").is_clerk_configured());
    }

    #[test]
    fn strips_the_sqlalchemy_driver_suffix() {
        assert_eq!(
            normalize_database_url("postgresql+psycopg://u:p@h:5432/db"),
            "postgresql://u:p@h:5432/db"
        );
    }

    /// The guard that turns a confusing pool error into a sentence. Each
    /// build accepts its own database and names the other binary for the
    /// other one, so this asserts both halves from whichever build runs.
    #[test]
    fn each_build_accepts_its_own_database_and_names_the_other() {
        let postgres = [
            "postgresql://u:p@h/db",
            "postgres://u:p@h/db",
            "POSTGRESQL://u:p@h/db",
        ];
        // The Python tier's documented default, which is also this one's.
        let sqlite = [
            "sqlite:///./sentinel.db",
            "sqlite:////data/sentinel.db",
            "sqlite:x.db",
        ];
        let (mine, theirs) = if crate::db::SQLITE {
            (sqlite, postgres)
        } else {
            (postgres, sqlite)
        };
        // Named after this binary, whatever it is called — the restore
        // tool has a sibling too.
        let other_binary = crate::db::sibling_binary_name(&crate::db::own_binary_name());
        for url in mine {
            assert!(unsupported_database_url(url).is_none(), "{url}");
        }
        for url in theirs {
            let message = unsupported_database_url(url).expect("refused");
            assert!(message.contains(&other_binary), "{url}: {message}");
            assert!(
                message.contains(crate::db::BACKEND_NAME),
                "{url}: {message}"
            );
        }
        for url in ["mysql://u@h/db", "/var/lib/sentinel.db", ""] {
            let message = unsupported_database_url(url).expect("refused");
            assert!(message.contains("sqlite://"), "{url:?}: {message}");
        }
    }

    #[test]
    fn leaves_a_plain_url_and_a_plus_in_the_password_alone() {
        for url in [
            "postgres://u:p@h/db",
            "postgresql://user:pa+ss@h/db",
            "sqlite:///./local.db",
        ] {
            assert_eq!(normalize_database_url(url), url);
        }
    }
}
