//! Environment configuration.
//!
//! Every name and default is carried over from the Python service's
//! `backend/app/core/config.py`. The Fly app's secrets are already set
//! against these names, so renaming one silently reverts it to a default
//! at the next deploy.

use std::env;

#[derive(Debug, Clone)]
pub struct Config {
    pub database_url: String,
    /// Port this process listens on. Rust owns the public 8000.
    pub port: u16,
    /// Where the Python app now listens, on localhost. Everything this
    /// service has not yet ported is proxied here — see `proxy.rs`.
    pub upstream: String,
    /// Directory holding the built SPA (`frontend/dist` copied to
    /// `/app/static` by the Dockerfile).
    pub static_dir: String,

    // --- Clerk ---------------------------------------------------------
    pub clerk_secret_key: String,
    pub clerk_publishable_key: String,
    /// Resolved from the publishable key; see `auth::issuer_from_publishable_key`.
    pub clerk_issuer: Option<String>,

    // --- local (self-hosted) auth --------------------------------------
    /// HS256 signing key for local session tokens.
    pub app_secret_key: String,
    pub local_org_id: String,
    pub local_admin_email: String,
    pub local_admin_username: String,
    /// Argon2 PHC string. Generated by
    /// `backend/scripts/hash_local_admin_password.py`.
    pub local_admin_password_hash: String,
    pub auth_provider: String,
    /// Shared storage for rate-limit counters.
    pub redis_url: String,

    /// Checked against a Clerk token's `azp` claim — the Python service
    /// passes it to the SDK as `authorized_parties`.
    pub frontend_url: String,
    /// Comma-separated extra CORS origins.
    pub cors_allowed_origins: String,
}

impl Config {
    /// `AUTH_PROVIDER=local`. Anything else, including a typo, falls
    /// through to Clerk — the safe default, and the exact complement the
    /// Python config documents.
    pub fn is_local_auth(&self) -> bool {
        self.auth_provider == "local"
    }

    /// All three of the local-auth secrets are set.
    ///
    /// The login and refresh routes answer 503 when this is false,
    /// rather than rejecting every password as wrong — an operator who
    /// forgot a secret needs to see a configuration problem.
    pub fn is_local_auth_configured(&self) -> bool {
        !self.app_secret_key.is_empty()
            && !self.local_admin_username.is_empty()
            && !self.local_admin_password_hash.is_empty()
    }

    pub fn is_clerk_configured(&self) -> bool {
        !self.clerk_secret_key.is_empty() && !self.clerk_publishable_key.is_empty()
    }
}

fn var_or(key: &str, default: &str) -> String {
    env::var(key).unwrap_or_else(|_| default.to_string())
}

impl Config {
    pub fn from_env() -> Self {
        let clerk_publishable_key = var_or("CLERK_PUBLISHABLE_KEY", "");
        Self {
            database_url: normalize_database_url(&var_or(
                "DATABASE_URL",
                "postgresql://postgres:postgres@localhost:5432/sentinel",
            )),
            port: var_or("PORT", "8000").parse().unwrap_or(8000),
            upstream: var_or("PYTHON_UPSTREAM", "http://127.0.0.1:8001"),
            static_dir: var_or("STATIC_DIR", "/app/static"),
            clerk_issuer: crate::auth::issuer_from_publishable_key(&clerk_publishable_key),
            clerk_secret_key: var_or("CLERK_SECRET_KEY", ""),
            clerk_publishable_key,
            app_secret_key: var_or("APP_SECRET_KEY", ""),
            // "self-host", not "local" — this string is the org_id every
            // row in a self-hosted install is scoped by, so a different
            // default here would make the Rust tier read and write a
            // different tenant than the Python one.
            local_org_id: var_or("LOCAL_ORG_ID", "self-host"),
            local_admin_email: var_or("LOCAL_ADMIN_EMAIL", ""),
            local_admin_username: var_or("LOCAL_ADMIN_USERNAME", ""),
            local_admin_password_hash: var_or("LOCAL_ADMIN_PASSWORD_HASH", ""),
            auth_provider: var_or("AUTH_PROVIDER", "clerk"),
            redis_url: var_or("REDIS_URL", ""),
            frontend_url: var_or("FRONTEND_URL", "http://localhost:5173"),
            cors_allowed_origins: var_or(
                "CORS_ALLOWED_ORIGINS",
                "https://app.sentinel-command.com",
            ),
        }
    }
}

/// Strip SQLAlchemy's `+driver` from a URL scheme.
///
/// The Fly secret holds `postgresql+psycopg://…`, which sqlx does not
/// understand. Normalising here means the secret does not have to be
/// rewritten during a migration that is already changing the runtime —
/// and it means both stacks can read the same variable while they run
/// side by side.
pub fn normalize_database_url(url: &str) -> String {
    match url.split_once("://") {
        Some((scheme, rest)) => match scheme.split_once('+') {
            Some((base, _driver)) => format!("{base}://{rest}"),
            None => url.to_string(),
        },
        None => url.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn config_with(auth_provider: &str, secret: &str, publishable: &str) -> Config {
        Config {
            database_url: String::new(),
            port: 8000,
            upstream: String::new(),
            static_dir: String::new(),
            clerk_secret_key: secret.into(),
            clerk_publishable_key: publishable.into(),
            clerk_issuer: None,
            app_secret_key: String::new(),
            local_org_id: "self-host".into(),
            local_admin_email: String::new(),
            local_admin_username: String::new(),
            local_admin_password_hash: String::new(),
            auth_provider: auth_provider.into(),
            redis_url: String::new(),
            frontend_url: String::new(),
            cors_allowed_origins: String::new(),
        }
    }

    #[test]
    fn anything_but_local_means_clerk() {
        // The Python config documents this as the safe default: a typo
        // in AUTH_PROVIDER must not silently disable authentication.
        assert!(config_with("local", "", "").is_local_auth());
        for provider in ["clerk", "", "Local", "locl", "none"] {
            assert!(
                !config_with(provider, "", "").is_local_auth(),
                "{provider:?} should not select local auth"
            );
        }
    }

    #[test]
    fn clerk_needs_both_keys_to_count_as_configured() {
        assert!(config_with("clerk", "sk", "pk").is_clerk_configured());
        assert!(!config_with("clerk", "sk", "").is_clerk_configured());
        assert!(!config_with("clerk", "", "pk").is_clerk_configured());
        assert!(!config_with("clerk", "", "").is_clerk_configured());
    }

    #[test]
    fn strips_the_sqlalchemy_driver_suffix() {
        assert_eq!(
            normalize_database_url("postgresql+psycopg://u:p@h:5432/db"),
            "postgresql://u:p@h:5432/db"
        );
    }

    #[test]
    fn leaves_a_plain_url_and_a_plus_in_the_password_alone() {
        for url in [
            "postgres://u:p@h/db",
            "postgresql://user:pa+ss@h/db",
            "sqlite:///./local.db",
        ] {
            assert_eq!(normalize_database_url(url), url);
        }
    }
}
