//! CPython's JSON decoder errors, message and position.
//!
//! FastAPI puts both into the 422 it returns for a malformed body:
//!
//! ```json
//! {"type": "json_invalid", "loc": ["body", 1], "msg": "JSON decode error",
//!  "input": {}, "ctx": {"error": "Expecting property name enclosed in double quotes"}}
//! ```
//!
//! serde_json finds the same errors and describes them differently —
//! `key must be a string at line 1 column 2` for the body `{x`, where
//! Python says the message above at *character* 1. Both strings are in
//! the response the SPA receives, so the port reproduces Python's.
//!
//! This follows `Modules/_json.c` as of Python 3.12 — the C scanner
//! `json.loads` uses — not the pure-Python fallback, and not 3.13, which
//! added "Illegal trailing comma". Positions are indices into the decoded
//! text in code points, as Python's are. Every message and position here
//! is checked against `tests/fixtures/pyjson_corpus.json`, generated by
//! the backend's own interpreter.

/// Why Python's `json.loads` would reject a text.
#[derive(Debug, PartialEq, Eq)]
pub enum DecodeError {
    /// A `JSONDecodeError`: FastAPI's `json_invalid` 422.
    Invalid { msg: &'static str, pos: usize },
    /// Nesting past the interpreter's recursion limit raises
    /// `RecursionError` instead, which FastAPI reports as a 400. The
    /// exact depth depends on Python's stack; this is an approximation.
    TooDeep,
}

const MAX_DEPTH: usize = 900;

/// `None` when Python would decode the text successfully — including
/// the three tokens Python accepts and JSON does not: `NaN`, `Infinity`
/// and `-Infinity`.
pub fn python_decode_error(text: &str) -> Option<DecodeError> {
    let s: Vec<char> = text.chars().collect();
    let mut d = Decoder { s: &s, depth: 0 };
    let start = d.skip_ws(0);
    let end = match d.scan_once(start) {
        Ok(end) => end,
        Err(Stop::Value(idx)) => {
            return Some(DecodeError::Invalid {
                msg: "Expecting value",
                pos: idx,
            })
        }
        Err(Stop::Msg(msg, pos)) => return Some(DecodeError::Invalid { msg, pos }),
        Err(Stop::TooDeep) => return Some(DecodeError::TooDeep),
    };
    let end = d.skip_ws(end);
    if end != s.len() {
        return Some(DecodeError::Invalid {
            msg: "Extra data",
            pos: end,
        });
    }
    None
}

enum Stop {
    /// `StopIteration(idx)`, which `raw_decode` turns into
    /// "Expecting value" wherever it was raised from.
    Value(usize),
    Msg(&'static str, usize),
    TooDeep,
}

struct Decoder<'a> {
    s: &'a [char],
    depth: usize,
}

fn is_ws(c: char) -> bool {
    matches!(c, ' ' | '\t' | '\n' | '\r')
}

impl Decoder<'_> {
    fn at(&self, i: usize) -> Option<char> {
        self.s.get(i).copied()
    }

    fn skip_ws(&self, mut i: usize) -> usize {
        while self.at(i).is_some_and(is_ws) {
            i += 1;
        }
        i
    }

    fn scan_once(&mut self, idx: usize) -> Result<usize, Stop> {
        let len = self.s.len();
        let Some(c) = self.at(idx) else {
            return Err(Stop::Value(idx));
        };
        let matches = |word: &str| {
            let w: Vec<char> = word.chars().collect();
            // `idx + n - 1 < length` in C, then a character compare.
            idx + w.len() <= len && self.s[idx..idx + w.len()] == w[..]
        };
        match c {
            '"' => return self.scanstring(idx + 1),
            '{' | '[' => {
                self.depth += 1;
                if self.depth > MAX_DEPTH {
                    return Err(Stop::TooDeep);
                }
                let r = if c == '{' {
                    self.object(idx + 1)
                } else {
                    self.array(idx + 1)
                };
                self.depth -= 1;
                return r;
            }
            'n' if matches("null") => return Ok(idx + 4),
            't' if matches("true") => return Ok(idx + 4),
            'f' if matches("false") => return Ok(idx + 5),
            'N' if matches("NaN") => return Ok(idx + 3),
            'I' if matches("Infinity") => return Ok(idx + 8),
            '-' if matches("-Infinity") => return Ok(idx + 9),
            _ => {}
        }
        self.number(idx)
    }

    /// `_match_number_unicode`. ASCII digits only — the C scanner does
    /// not accept Unicode digits, though the pure-Python regex would.
    fn number(&self, start: usize) -> Result<usize, Stop> {
        let s = self.s;
        let end_idx = s.len() as isize - 1;
        let digit = |i: usize| s.get(i).is_some_and(|c| c.is_ascii_digit());
        let mut idx = start;
        if s.get(idx) == Some(&'-') {
            idx += 1;
            if idx as isize > end_idx {
                return Err(Stop::Value(start));
            }
        }
        match s.get(idx) {
            Some(c) if ('1'..='9').contains(c) => {
                idx += 1;
                while digit(idx) {
                    idx += 1;
                }
            }
            Some('0') => idx += 1,
            _ => return Err(Stop::Value(start)),
        }
        // `idx < end_idx`: a '.' needs a digit after it, and the check is
        // strict, so "1." is the number 1 followed by extra data.
        if (idx as isize) < end_idx && s[idx] == '.' && digit(idx + 1) {
            idx += 2;
            while digit(idx) {
                idx += 1;
            }
        }
        if (idx as isize) < end_idx && (s[idx] == 'e' || s[idx] == 'E') {
            let e_start = idx;
            idx += 1;
            if (idx as isize) < end_idx && (s[idx] == '-' || s[idx] == '+') {
                idx += 1;
            }
            while digit(idx) {
                idx += 1;
            }
            // No exponent digits: back off and leave the 'e' as extra data.
            if !digit(idx - 1) {
                idx = e_start;
            }
        }
        Ok(idx)
    }

    /// `scanstring_unicode` with `strict=True`. `end` is the index just
    /// past the opening quote.
    fn scanstring(&self, mut end: usize) -> Result<usize, Stop> {
        let s = self.s;
        let len = s.len();
        let begin = end - 1;
        loop {
            let mut next = end;
            let mut c = '\0';
            while next < len {
                c = s[next];
                if c == '"' || c == '\\' {
                    break;
                }
                if (c as u32) <= 0x1f {
                    return Err(Stop::Msg("Invalid control character at", next));
                }
                next += 1;
            }
            if next >= len || !(c == '"' || c == '\\') {
                return Err(Stop::Msg("Unterminated string starting at", begin));
            }
            if c == '"' {
                return Ok(next + 1);
            }
            // A backslash.
            next += 1;
            if next == len {
                return Err(Stop::Msg("Unterminated string starting at", begin));
            }
            let e = s[next];
            if e != 'u' {
                end = next + 1;
                if !matches!(e, '"' | '\\' | '/' | 'b' | 'f' | 'n' | 'r' | 't') {
                    return Err(Stop::Msg("Invalid \\escape", end - 2));
                }
                continue;
            }
            next += 1;
            end = next + 4;
            if end >= len {
                return Err(Stop::Msg("Invalid \\uXXXX escape", next - 1));
            }
            let mut code: u32 = 0;
            while next < end {
                let Some(v) = s[next].to_digit(16) else {
                    return Err(Stop::Msg("Invalid \\uXXXX escape", end - 5));
                };
                code = (code << 4) | v;
                next += 1;
            }
            // A high surrogate followed by `\u` is read as a pair when
            // there is room; a low half that is not in fact low leaves
            // the second escape to be read again on its own.
            if (0xD800..0xDC00).contains(&code)
                && end + 6 < len
                && s[next] == '\\'
                && s[next + 1] == 'u'
            {
                next += 2;
                end += 6;
                let mut low: u32 = 0;
                while next < end {
                    let Some(v) = s[next].to_digit(16) else {
                        return Err(Stop::Msg("Invalid \\uXXXX escape", end - 5));
                    };
                    low = (low << 4) | v;
                    next += 1;
                }
                if !(0xDC00..0xE000).contains(&low) {
                    end -= 6;
                }
            }
        }
    }

    /// `_parse_object_unicode`, entered just past `{`.
    fn object(&mut self, idx: usize) -> Result<usize, Stop> {
        let mut idx = self.skip_ws(idx);
        if self.at(idx) != Some('}') {
            loop {
                if self.at(idx) != Some('"') {
                    return Err(Stop::Msg(
                        "Expecting property name enclosed in double quotes",
                        idx,
                    ));
                }
                idx = self.scanstring(idx + 1)?;
                idx = self.skip_ws(idx);
                if self.at(idx) != Some(':') {
                    return Err(Stop::Msg("Expecting ':' delimiter", idx));
                }
                idx = self.skip_ws(idx + 1);
                idx = self.scan_once(idx)?;
                idx = self.skip_ws(idx);
                if self.at(idx) == Some('}') {
                    break;
                }
                if self.at(idx) != Some(',') {
                    return Err(Stop::Msg("Expecting ',' delimiter", idx));
                }
                idx = self.skip_ws(idx + 1);
            }
        }
        Ok(idx + 1)
    }

    /// `_parse_array_unicode`, entered just past `[`.
    fn array(&mut self, idx: usize) -> Result<usize, Stop> {
        let mut idx = self.skip_ws(idx);
        if self.at(idx) != Some(']') {
            loop {
                idx = self.scan_once(idx)?;
                idx = self.skip_ws(idx);
                if self.at(idx) == Some(']') {
                    break;
                }
                if self.at(idx) != Some(',') {
                    return Err(Stop::Msg("Expecting ',' delimiter", idx));
                }
                idx = self.skip_ws(idx + 1);
            }
        }
        Ok(idx + 1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_corpus_entry_matches_cpython() {
        // Generated by the backend's Python 3.12 — see the module docs.
        let corpus: serde_json::Value =
            serde_json::from_str(include_str!("../tests/fixtures/pyjson_corpus.json")).unwrap();
        let mut checked = 0;
        for entry in corpus.as_array().unwrap() {
            let text = entry["text"].as_str().unwrap();
            // A leading BOM is only an error for a `str` argument. FastAPI
            // passes bytes, which `json.loads` decodes as utf-8-sig, so the
            // body never contains one by the time it is scanned.
            if text.starts_with('\u{feff}') {
                continue;
            }
            let got = python_decode_error(text);
            if entry["ok"].as_bool().unwrap() {
                assert_eq!(got, None, "python accepts {text:?}");
            } else {
                let want_msg = entry["msg"].as_str().unwrap();
                let want_pos = entry["pos"].as_u64().unwrap() as usize;
                match got {
                    Some(DecodeError::Invalid { msg, pos }) => {
                        assert_eq!((msg, pos), (want_msg, want_pos), "input {text:?}");
                    }
                    other => {
                        panic!("input {text:?}: expected {want_msg:?} at {want_pos}, got {other:?}")
                    }
                }
            }
            checked += 1;
        }
        assert!(checked > 60, "the corpus shrank to {checked} entries");
    }

    #[test]
    fn deep_nesting_is_reported_rather_than_overflowing_the_stack() {
        let text = "[".repeat(100_000);
        assert_eq!(python_decode_error(&text), Some(DecodeError::TooDeep));
    }
}
