#!/usr/bin/env python3
"""Regenerate src/tz_names.rs from the backend's tzdata package.

`zoneinfo.available_timezones()` is that package's `zones` file plus a
walk of the system zoneinfo directories. src/zoneinfo.rs does the walk
itself, at request time, as the Python does — so this embeds only the
half Rust cannot reach: the package's own list. src/zoneinfo.rs also
loads the package's zones from jiff's bundled database, and a test there
fails unless that is the same IANA release recorded here.

Run it with the backend's interpreter after bumping tzdata; the diff
shows precisely which names changed.

Usage: backend/.venv/bin/python tests/differential/gen_tz_names.py
"""
import pathlib
from importlib import resources

import tzdata  # a hard dependency of the backend, not an optional one

version = tzdata.IANA_VERSION
# Exactly as available_timezones() reads it: strip each line, skip blanks.
zones = resources.files("tzdata").joinpath("zones").read_text()
names = sorted({line.strip() for line in zones.splitlines() if line.strip()})

out = pathlib.Path(__file__).resolve().parents[2] / "src" / "tz_names.rs"
lines = [
    "//! The zone names the backend's tzdata package lists in its `zones`",
    f"//! file (tzdata {version}, {len(names)} names).",
    "//!",
    "//! `crate::zoneinfo` adds the system directories to these at request",
    "//! time, as `zoneinfo.available_timezones()` does.",
    "//!",
    "//! Generated by tests/differential/gen_tz_names.py — do not edit by",
    "//! hand. Regenerate after bumping tzdata in the backend.",
    "",
    f"pub const TZDATA_VERSION: &str = \"{version}\";",
    "",
    "/// Sorted, so membership is a binary search.",
    "pub const NAMES: &[&str] = &[",
    *[f'    "{n}",' for n in names],
    "];",
    "",
    "pub fn is_valid(name: &str) -> bool {",
    "    NAMES.binary_search(&name).is_ok()",
    "}",
    "",
]
out.write_text("\n".join(lines))
print(f"wrote {len(names)} names (tzdata {version}) to {out}")
