"""
Notifications API — unified inbox for user-facing events.

Covers motion detection alerts, camera/node status transitions, and
(future) system errors.  Supports:
  - GET  /api/notifications             list recent, paginated, audience-filtered
  - GET  /api/notifications/unread-count badge count for the bell icon
  - POST /api/notifications/mark-viewed  bump the user's last_viewed_at to now
  - GET  /api/notifications/stream       SSE — live updates for the panel

Read state is per-(clerk_user_id, org_id).  Unread = notifications newer
than the user's last_viewed_at timestamp.

Audience filtering: each notification has ``audience`` set to ``"all"``
(every member sees it) or ``"admin"`` (only admins see it).  Non-admin
users never see ``"admin"`` notifications in their feed or unread count.
"""

import asyncio
import json
import logging
import time as _time
from datetime import UTC, datetime, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request
from fastapi.responses import HTMLResponse, StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.audit import audit_label, write_audit
from app.core.auth import AuthUser, require_admin, require_view
from app.core.config import settings
from app.core.database import SessionLocal, get_db
from app.core.email_unsubscribe import verify_token
from app.core.limiter import limiter
from app.core.recipients import get_recipient_emails
from app.models.models import (
    EmailOutbox,
    Notification,
    Setting,
    UserNotificationState,
)

# ── Per-org preference gate ────────────────────────────────────────
# Which notification kinds the org wants delivered to the inbox.
# Defaults intentionally match "everything on" so behaviour before the
# settings UI shipped is unchanged — operators only ever see less noise
# than before, never more.  Keys map kind → (setting_key, default).

_NOTIFICATION_KIND_TO_SETTING: dict[str, tuple[str, bool]] = {
    "motion": ("motion_notifications", True),
    # motion_digest shares motion's inbox toggle — if you've muted
    # motion in the bell-icon panel, you don't want a digest banner
    # either.  Generated by _motion_digest_loop in app/main.py when
    # an email cooldown window expires with extra events accumulated.
    "motion_digest": ("motion_notifications", True),
    "camera_online": ("camera_transition_notifications", True),
    "camera_offline": ("camera_transition_notifications", True),
    "node_online": ("node_transition_notifications", True),
    "node_offline": ("node_transition_notifications", True),
    # MCP key lifecycle — security audit signal that's worth seeing
    # in the bell-icon panel even for admins who turned off the
    # email side-channel.  Both events share one inbox toggle key
    # for the same reason the email side does (admins want both
    # or neither).
    "mcp_key_created": ("mcp_key_audit_notifications", True),
    "mcp_key_revoked": ("mcp_key_audit_notifications", True),
    # CloudNode-side disk warning.  Customer hardware running their
    # own CloudNode has filled past the threshold — recordings will
    # fail when it caps out.  Customer-actionable (clean up files,
    # expand storage), unlike our Command Center disk which is
    # operator-side and routed via Sentry.
    "cloudnode_disk_low": ("cloudnode_disk_notifications", True),
    # Org membership lifecycle (security audit) — fired by Clerk
    # webhooks.  All three share a single inbox toggle; same logic
    # as the email side (admins want the whole audit trail or none
    # of it, not "I care about additions but not removals").
    "member_added":        ("member_audit_notifications", True),
    "member_role_changed": ("member_audit_notifications", True),
    "member_removed":      ("member_audit_notifications", True),
    # Member-initiated promotion request — fired by a non-admin
    # member clicking "Request admin access" from the dashboard.
    # Shares the member-audit toggle because it's the same audience
    # decision: admins want the whole member-lifecycle audit trail
    # or none of it.  Defaults True so admins never miss a request
    # to grant programmatic / write access to their org.
    "member_promotion_requested": ("member_audit_notifications", True),
    # First-touch onboarding — fired once when an org is created.
    # Has its own setting key (no UI toggle today) so a future
    # "marketing email opt-out" change has somewhere to land
    # without conflating with the operational kinds above.  Default
    # True because welcome is a one-time event, not a stream.
    "welcome": ("welcome_notifications", True),
}


# ── Email side-channel preference gate ─────────────────────────────
# Per-org per-kind "should we email this notification?" toggle.  The
# inbox gate above (_NOTIFICATION_KIND_TO_SETTING) decides whether
# the notification appears in the bell-icon panel; this map decides
# whether it ALSO emails out.
#
# Different defaults from the inbox gate on purpose:
#   - The "online" recovery events are NOT emailed even when the
#     "offline" events are — recovery is good news that doesn't need
#     a midnight email.  Keeps the inbox feed and the email feed
#     intentionally different shapes.
#   - Motion is in the map but defaults FALSE — see the motion +
#     motion_digest entries below for the full rationale.  v1.1
#     ships motion email with per-camera cooldown + digest summary
#     so volume is bounded; we still default-off because per-org
#     volume variance is too high to opt users in by default.
#   - All other defaults are True so an org that hasn't visited the
#     settings page still gets the operator-critical alerts.
#
# When EMAIL_ENABLED is False globally (the kill-switch), this gate
# is bypassed entirely and no rows get enqueued — we don't enqueue
# rows just to have the worker discard them.
_EMAIL_KIND_TO_SETTING: dict[str, tuple[str, bool]] = {
    "camera_offline":   ("email_camera_offline",   True),
    # camera_online intentionally shares the camera_offline setting
    # key — one toggle controls the whole transition pair so users
    # don't have to opt in twice for "I want to know about my
    # camera's connection state."  If you got the offline email at
    # 3am, you want the recovery email when it comes back so you
    # can stop worrying — same toggle, same intent.
    "camera_online":    ("email_camera_offline",   True),
    "node_offline":     ("email_node_offline",     True),
    "node_online":      ("email_node_offline",     True),
    "incident_created": ("email_incident_created", True),
    # MCP key lifecycle = security audit signal.  Both create and
    # revoke share one setting key (admins want both or neither —
    # there's no "I care about new keys but not revocations" use
    # case).  Defaults ON because new MCP keys = full programmatic
    # access; nobody should miss that being granted.
    "mcp_key_created":  ("email_mcp_key_audit",    True),
    "mcp_key_revoked":  ("email_mcp_key_audit",    True),
    # CloudNode host disk approaching full.  Customer hardware,
    # customer-actionable, separate from the Command Center disk
    # we route via Sentry (operator-side).
    "cloudnode_disk_low": ("email_cloudnode_disk_low", True),
    # Org membership lifecycle = high-value security audit signal.
    # All three events (add, role change, remove) share one setting
    # key — admins consistently want the whole audit trail or none
    # of it.  Defaults ON because admin escalation is the kind of
    # thing nobody should miss happening to their org.
    "member_added":        ("email_member_audit", True),
    "member_role_changed": ("email_member_audit", True),
    "member_removed":      ("email_member_audit", True),
    # Member-initiated promotion request — same setting key as the
    # other member-lifecycle events.  Defaults True because granting
    # admin access is exactly the kind of decision an admin should
    # see proactively, not have to discover by checking the bell
    # icon at random intervals.
    "member_promotion_requested": ("email_member_audit", True),
    # Motion detection — high volume, deferred to v1.1 cooldown design.
    # Both kinds (immediate first-event "motion" + cooldown summary
    # "motion_digest") share email_motion.  DEFAULT FALSE on purpose:
    # motion volume is wildly variable per customer (1 indoor doorbell
    # vs. 10 outdoor cameras), and opting users in by default risks
    # surprise day-one volume on outdoor cams → spam-marks → tanks
    # Resend sender reputation for ALL email kinds across ALL customers.
    # Customers explicitly opt in via the Settings UI toggle.
    # Volume cap mechanism: app/api/notifications.py::_claim_motion_cooldown_or_silence
    # silences subsequent events within the cooldown window per camera;
    # app/main.py::_motion_digest_loop emits ONE summary at window
    # close.  Worst case: 2 emails per cycle per camera regardless of
    # event volume.
    "motion":        ("email_motion", False),
    "motion_digest": ("email_motion", False),
    # First-touch welcome on org creation.  Own setting key with no UI
    # toggle today — operators can flip via direct DB write if they
    # need to suppress (e.g. an internal test org).  Default True
    # because the whole point of the kind is to introduce the product;
    # an opt-in default would make the gap we're closing reappear.
    "welcome": ("email_welcome", True),
}
# Note: ``disk_critical`` is intentionally NOT in this map.  Disk-full
# is platform infrastructure state (our Fly volume) — irrelevant to
# customer org admins, who can't act on it and shouldn't be paged
# about our infra.  Operator-side disk monitoring lives in three
# existing channels instead: ``/api/health/detailed`` (status-page-
# pollable), Sentry (catches the actual SQLite write failures when
# disk fills), Fly's resource dashboards.  Adding disk_critical
# back here would re-create the multi-tenant violation we removed
# in 2026-05-04.


def notifications_enabled(db: Session, org_id: str, kind: str) -> bool:
    """Return True if notifications of ``kind`` should be delivered for
    ``org_id``.  Unknown kinds default to enabled so new notification
    types don't silently disappear when added without a settings migration.

    Reads from the ``Setting`` table using the same "string value" pattern
    the recording toggles use.  Keeping it here (not in the motion path)
    means every emitter can gate without duplicating the lookup logic.
    """
    cfg = _NOTIFICATION_KIND_TO_SETTING.get(kind)
    if cfg is None:
        return True
    key, default = cfg
    val = Setting.get(db, org_id, key, None)
    if val is None:
        return default
    return val == "true"


def email_enabled_for_kind(db: Session, org_id: str, kind: str) -> bool:
    """Return True if this org wants ``kind`` notifications emailed out.

    Two gates in series:
      1. ``settings.EMAIL_ENABLED`` — global kill-switch.  If False, no
         org gets emails regardless of their per-kind preference.
      2. Per-org per-kind setting in the ``Setting`` table.  Defaults
         from ``_EMAIL_KIND_TO_SETTING`` apply when the row is absent.

    Unknown kinds return False — the inbox gate defaults unknown kinds
    to ENABLED for forward-compat, but the email gate is the opposite:
    we'd rather miss emailing a brand-new kind than blast users on it
    by default before the per-kind setting UI catches up.
    """
    if not settings.EMAIL_ENABLED:
        return False
    cfg = _EMAIL_KIND_TO_SETTING.get(kind)
    if cfg is None:
        return False
    key, default = cfg
    val = Setting.get(db, org_id, key, None)
    if val is None:
        return default
    return val == "true"


# ── Motion email cooldown ──────────────────────────────────────────
# Per-camera cooldown anchor mechanism.  Used by the email branch of
# create_notification (when kind="motion") to silence per-event emails
# that arrive during an active window, AND by ``_motion_digest_loop``
# in app/main.py to find expired anchors and emit the summary.
#
# Anchor data: a Setting row per (org_id, camera_id) where the key is
# ``motion_email_cooldown_start:{camera_id}`` and the value is the ISO
# timestamp of when the immediate email was sent.  The colon-suffix
# pattern matches the ``cloudnode_disk_low_emit_at:{node_id}``
# precedent in app/api/nodes.py:72-121.
#
# Lifecycle: written by _claim_motion_cooldown_or_silence on the first
# motion event after expiry, read by both subsequent in-window events
# (which silence) and the digest loop (which emits + deletes), deleted
# by the digest loop after the window closes.  Persistent across
# process restarts which is the whole reason for using Setting over an
# in-memory dict — a deploy mid-window must NOT re-spam users.


def _motion_cooldown_anchor_key(camera_id: str) -> str:
    """Setting key for the per-camera motion email cooldown anchor.

    Mirrors the ``cloudnode_disk_low_emit_at:{node_id}`` pattern in
    app/api/nodes.py — colon-suffix so the digest loop can find all
    active anchors with a single ``Setting.key.like("motion_email_cooldown_start:%")``
    query, and parse the camera_id back out by splitting on ":".
    """
    return f"motion_email_cooldown_start:{camera_id}"


def _motion_cooldown_minutes(db: Session, org_id: str) -> int:
    """Per-org cooldown duration in minutes.  Default 15.

    Hidden setting for v1.1 — operators set it via direct DB write or
    a future env-bootstrap.  Min 1 (no point in zero — the immediate
    fires anyway).  Falls back to 15 on any parse failure so a
    corrupt value can't disable emails entirely.
    """
    raw = Setting.get(db, org_id, "email_motion_cooldown_minutes", "15")
    try:
        return max(1, int(raw))
    except (ValueError, TypeError):
        return 15


def _claim_motion_cooldown_or_silence(
    db: Session, org_id: str, camera_id: Optional[str]
) -> bool:
    """Returns True if this event should email immediately (and writes
    the anchor as a side effect); False if a cooldown anchor is active
    and the event should be silenced.

    Concurrency note: read-then-write is non-atomic in SQLite without
    an explicit transaction.  Two motion events arriving in the same
    microsecond could both see "anchor missing" and both enqueue an
    immediate email.  Worst case is one duplicate first-event email,
    which we accept (matches the cloudnode_disk_low precedent and is
    far better than silently losing alerts).  If/when we go multi-
    replica, swap to a dedicated table with INSERT...ON CONFLICT.
    """
    if camera_id is None:
        # Defensive — motion notifications today always carry a camera_id
        # (see ws.py emit), but a future caller without one shouldn't
        # silently break.  Default to "send immediate" rather than
        # "silence" because a missing camera_id would also break the
        # digest loop's per-camera grouping.
        return True

    key = _motion_cooldown_anchor_key(camera_id)
    existing = Setting.get(db, org_id, key, "")
    cooldown_min = _motion_cooldown_minutes(db, org_id)
    now = datetime.now(tz=UTC).replace(tzinfo=None)

    if existing:
        try:
            anchor = datetime.fromisoformat(existing)
            if (now - anchor).total_seconds() < cooldown_min * 60:
                return False  # silenced — within active cooldown window
        except ValueError:
            # Malformed value (manual edit / corruption).  Treat as
            # expired and overwrite below — better than refusing to
            # email forever.
            pass

    Setting.set(db, org_id, key, now.isoformat())
    return True


def _build_email_content(notif: Notification) -> tuple[str, str, str]:
    """Render a notification into ``(subject, body_text, body_html)``
    via the Jinja2 templates in ``app/templates/emails/``.

    Thin wrapper around ``app.core.email_templates.render`` — the
    interesting work lives there.  This wrapper exists so callers in
    ``create_notification()`` don't need to know about the
    unsubscribe-token path, the dashboard URL config, or the
    template module's import shape.
    """
    from app.core import email_templates

    # Render ONCE with a placeholder; the enqueue loop substitutes a
    # per-recipient signed URL into each outbox row.  Unsubscribe tokens
    # carry the recipient address (per-address suppression), so a shared
    # URL across recipients is no longer possible — and re-rendering the
    # full template per recipient would be pure waste.  The placeholder
    # contains no HTML-special characters, so it passes through both the
    # text and autoescaped HTML templates verbatim.
    return email_templates.render(
        notif.kind,
        notif,
        unsubscribe_url=_UNSUB_URL_PLACEHOLDER,
    )


# Substituted per-recipient at enqueue time — see _build_email_content.
# No &, <, >, ", or % so it survives both the text template and Jinja2
# autoescape unchanged.
_UNSUB_URL_PLACEHOLDER = "UNSUB-URL-PLACEHOLDER-7f3a"


def _enqueue_email_for_notification(
    session: Session, notif: Notification, audience: str
) -> int:
    """Look up recipients and insert one EmailOutbox row per address.

    Returns the count of rows enqueued (zero on any failure).  Never
    raises — this is called from inside ``create_notification`` and a
    failure here must not roll back the inbox notification we just
    committed.

    Caller must have already verified ``email_enabled_for_kind()`` is
    True; this function unconditionally enqueues for the audience.
    """
    try:
        recipients = get_recipient_emails(notif.org_id, audience)
    except Exception:
        logger.exception(
            "[Notifications] recipient lookup failed for org=%s kind=%s",
            notif.org_id, notif.kind,
        )
        return 0

    if not recipients:
        return 0

    try:
        subject, body_text, body_html = _build_email_content(notif)
    except Exception:
        logger.exception(
            "[Notifications] email template render failed for kind=%s",
            notif.kind,
        )
        return 0

    enqueued = 0
    for addr in recipients:
        try:
            # Per-recipient unsubscribe URL — the token binds the
            # recipient address so a click suppresses THAT address,
            # not the whole org's toggle.
            from app.core.email_unsubscribe import build_unsubscribe_url
            unsub_url = build_unsubscribe_url(notif.org_id, notif.kind, addr)
            session.add(EmailOutbox(
                org_id=notif.org_id,
                recipient_email=addr,
                subject=subject,
                body_text=body_text.replace(_UNSUB_URL_PLACEHOLDER, unsub_url),
                body_html=body_html.replace(_UNSUB_URL_PLACEHOLDER, unsub_url),
                kind=notif.kind,
                notification_id=notif.id,
                status="pending",
            ))
            enqueued += 1
        except Exception:
            logger.exception(
                "[Notifications] enqueue failed for org=%s kind=%s addr=%s",
                notif.org_id, notif.kind, addr,
            )

    if enqueued:
        try:
            session.commit()
        except Exception:
            logger.exception(
                "[Notifications] outbox commit failed for kind=%s", notif.kind,
            )
            try:
                session.rollback()
            except Exception:
                pass
            return 0

    return enqueued

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/notifications", tags=["notifications"])


# ── Broadcaster ─────────────────────────────────────────────────────
# Same pattern as motion_broadcaster — one asyncio.Queue per SSE
# subscriber, scoped by org.  Each event also carries the audience so
# the stream generator can filter per subscriber.

# Per-org SSE subscriber cap. Tiered — see the matching comment in motion.py.
# This module-level constant is the fallback; route handlers pass the
# plan-specific cap from ``app.core.plans.PLAN_LIMITS``.
MAX_SSE_SUBSCRIBERS_PER_ORG = 100  # fallback — Pro Plus default


class NotificationBroadcaster:
    """Push notification events to inbox SSE subscribers, scoped by org."""

    def __init__(self):
        # {org_id: [(queue, is_admin), ...]}
        self._subscribers: dict[str, list[tuple[asyncio.Queue, bool]]] = {}

    def notify(self, org_id: str, event_data: dict):
        """Broadcast a notification to every SSE subscriber in the org.

        Subscribers get the event only if their role matches the event's
        audience ("all" is delivered to everyone; "admin" only to admins).
        """
        audience = event_data.get("audience", "all")
        subs = self._subscribers.get(org_id, [])
        dead = []
        for q, is_admin in subs:
            if audience == "admin" and not is_admin:
                continue
            try:
                q.put_nowait(event_data)
            except asyncio.QueueFull:
                dead.append((q, is_admin))
        if dead:
            for entry in dead:
                try:
                    self._subscribers[org_id].remove(entry)
                except (ValueError, KeyError):
                    pass

    def subscribe(
        self,
        org_id: str,
        is_admin: bool,
        cap: int = MAX_SSE_SUBSCRIBERS_PER_ORG,
    ) -> Optional[asyncio.Queue]:
        """Add a new SSE subscription for an org.

        ``cap`` is the per-tier subscriber cap the caller looked up (see
        PLAN_LIMITS). Returns the queue on success, or ``None`` when this
        org is already at the cap — the route handler translates that into
        a 429.
        """
        existing = self._subscribers.setdefault(org_id, [])
        if len(existing) >= cap:
            logger.warning(
                "[Notifications] SSE cap hit for org %s (%d/%d) — rejecting",
                org_id, len(existing), cap,
            )
            return None
        q: asyncio.Queue = asyncio.Queue(maxsize=100)
        existing.append((q, is_admin))
        logger.info(
            "[Notifications] SSE subscriber added for org %s (admin=%s, %d/%d)",
            org_id, is_admin, len(existing), cap,
        )
        return q

    def unsubscribe(self, org_id: str, q: asyncio.Queue):
        subs = self._subscribers.get(org_id)
        if not subs:
            return
        self._subscribers[org_id] = [(qq, adm) for qq, adm in subs if qq is not q]


notification_broadcaster = NotificationBroadcaster()


# ── Service ────────────────────────────────────────────────────────
# Helper that any part of the app can call to emit a notification.
# Handles DB persistence + broadcast.  Swallows errors so a bad
# notification never takes down the caller.

def create_notification(
    org_id: str,
    kind: str,
    title: str,
    *,
    body: str = "",
    severity: str = "info",
    audience: str = "all",
    link: Optional[str] = None,
    camera_id: Optional[str] = None,
    node_id: Optional[str] = None,
    meta: Optional[dict] = None,
    db: Optional[Session] = None,
) -> Optional[Notification]:
    """Persist a notification and broadcast it to subscribers.

    Pass ``db`` to reuse an existing session (recommended when called
    from inside a request handler that already has one); otherwise a
    fresh SessionLocal is opened and closed here.
    Returns the saved Notification or None on failure.
    """
    owns_session = db is None
    session = db or SessionLocal()

    if audience not in ("all", "admin"):
        audience = "all"
    if severity not in ("info", "warning", "error", "critical"):
        severity = "info"

    # Per-org INBOX preference gate — an operator who turned off
    # "motion notifications" in Settings should stop seeing new motion
    # rows in the inbox without affecting the motion-event pipeline
    # itself.  Done here (vs. at each call site) so every emitter,
    # current and future, automatically respects the toggle.
    #
    # Scope: this gate controls ONLY the inbox row + SSE broadcast.
    # The email side-channel and the Sentinel-agent dispatch below run
    # regardless, because the UI presents them as independent controls:
    # the Settings page has separate inbox and email toggles per kind,
    # and Sentinel has its own enabled/trigger/scope config.  (An
    # earlier version early-returned here, which silently killed
    # "email ON + inbox OFF" combinations and blinded the agent when
    # bell noise was muted.)
    inbox_enabled = True
    try:
        inbox_enabled = notifications_enabled(session, org_id, kind)
    except Exception:
        # Gate failures must not block notifications — fall through to
        # the normal create path so we're no worse off than before the
        # gate existed.
        logger.exception("[Notifications] preference lookup failed; emitting anyway")

    try:
        notif = Notification(
            org_id=org_id,
            kind=kind,
            audience=audience,
            title=title[:200],
            body=body or "",
            severity=severity,
            link=link,
            camera_id=camera_id,
            node_id=node_id,
            meta_json=json.dumps(meta) if meta else None,
        )
        if inbox_enabled:
            session.add(notif)
            session.commit()
            session.refresh(notif)

            # Broadcast after commit so subscribers never see a row that
            # could later be rolled back.
            payload = notif.to_dict()
            payload["type"] = "notification"
            payload["audience"] = audience
            notification_broadcaster.notify(org_id, payload)
        # else: notif stays transient — never added to the session.  The
        # email templates only read constructor-set fields (title, body,
        # link, meta…), and EmailOutbox.notification_id is a nullable
        # soft reference, so the side-channels below work unchanged.

        # Email side-channel.  Same gate pattern as the inbox
        # preference, different setting key.  Failure never blocks
        # the caller — the inbox notification is already committed
        # and a missing email is recoverable (operator can re-trigger
        # the alert), but a failure that propagated out of here
        # would prevent the notification from showing up in the
        # bell panel too.
        try:
            if email_enabled_for_kind(session, org_id, kind):
                if kind == "motion":
                    # v1.1 cooldown gate: only email the FIRST motion
                    # event per camera per cooldown window.  Subsequent
                    # in-window events still hit the inbox + SSE above
                    # but skip the email outbox.  ``_motion_digest_loop``
                    # in app/main.py picks up expired anchors and
                    # emits a single ``motion_digest`` summary.
                    if _claim_motion_cooldown_or_silence(session, org_id, camera_id):
                        _enqueue_email_for_notification(session, notif, audience)
                    # else: silenced — digest will summarise
                else:
                    _enqueue_email_for_notification(session, notif, audience)
        except Exception:
            logger.exception(
                "[Notifications] email enqueue side-channel failed for kind=%s",
                kind,
            )

        # Sentinel agent dispatch — see app/core/sentinel_dispatch.py.
        # The dispatcher gates on Sentinel config (enabled, trigger
        # toggles, camera scope, schedule window, monthly cap) and
        # creates a pending sentinel_runs row when the gate clears.
        # Best-effort and self-contained: a dispatch failure never
        # blocks the underlying notification from being delivered.
        try:
            from app.core.sentinel_dispatch import maybe_dispatch_for_notification
            maybe_dispatch_for_notification(
                session, org_id=org_id, kind=kind, camera_id=camera_id,
            )
        except Exception:
            logger.exception(
                "[Notifications] sentinel dispatch failed for kind=%s",
                kind,
            )

        # Preserve the long-standing contract: callers get the persisted
        # row, or None when the inbox preference suppressed it (even
        # though the side-channels above may still have fired).
        return notif if inbox_enabled else None
    except Exception:
        logger.exception("[Notifications] Failed to create notification")
        try:
            session.rollback()
        except Exception:
            pass
        return None
    finally:
        if owns_session:
            session.close()


# ── Status transitions (online ↔ offline) ─────────────────────────
# Cameras/nodes flap: a node with a spotty uplink can toggle online/
# offline every few seconds.  We debounce per-(entity, direction) so
# the inbox doesn't drown in duplicates.  The debounce is in-memory
# only — acceptable because the worst case after a process restart is
# one extra notification, and notifications are append-only anyway.

_TRANSITION_DEBOUNCE_SECONDS = 60
_transition_debounce: dict[tuple[str, str, str], float] = {}


def _should_emit_transition(kind: str, entity_id: str, direction: str) -> bool:
    """Return True if we haven't emitted this (kind,entity,direction)
    recently.  Updates the timestamp on a positive return so subsequent
    calls within the debounce window are suppressed.

    The sentinel for "never emitted before" is ``-inf``, not ``0.0`` —
    otherwise on a freshly-booted host (e.g. GitHub Actions runners,
    where ``time.monotonic()`` starts near zero) the very first emit
    can fall inside the debounce window and get silently dropped.
    """
    key = (kind, entity_id, direction)
    now = _time.monotonic()
    last = _transition_debounce.get(key, float("-inf"))
    if now - last < _TRANSITION_DEBOUNCE_SECONDS:
        return False
    _transition_debounce[key] = now
    return True


def clear_transition_debounce() -> None:
    """Reset the in-memory debounce map.  Exposed for tests."""
    _transition_debounce.clear()


def emit_camera_transition(
    db: Session,
    *,
    camera_id: str,
    org_id: str,
    display_name: str,
    new_status: str,
    node_id: Optional[str] = None,
) -> Optional[Notification]:
    """Emit a camera online↔offline transition notification.

    Audience is ``"all"`` — every org member cares when a camera drops.
    Debounced per-(camera, direction) to survive flaps.
    """
    if new_status not in ("online", "offline"):
        return None
    if not _should_emit_transition("camera", camera_id, new_status):
        return None

    kind = "camera_online" if new_status == "online" else "camera_offline"
    return create_notification(
        org_id=org_id,
        kind=kind,
        title=f"{display_name} is online" if new_status == "online" else f"{display_name} went offline",
        body="Camera is streaming again." if new_status == "online" else "No heartbeat received in over 90 seconds.",
        severity="info" if new_status == "online" else "warning",
        audience="all",
        link=f"/dashboard?camera={camera_id}",
        camera_id=camera_id,
        node_id=node_id,
        db=db,
    )


def emit_node_transition(
    db: Session,
    *,
    node_id: str,
    org_id: str,
    display_name: str,
    new_status: str,
) -> Optional[Notification]:
    """Emit a node online↔offline transition notification.

    Audience is ``"admin"`` — node health is an operator concern; regular
    viewers don't need to know about CloudNode uplink status.
    """
    if new_status not in ("online", "offline"):
        return None
    if not _should_emit_transition("node", node_id, new_status):
        return None

    kind = "node_online" if new_status == "online" else "node_offline"
    return create_notification(
        org_id=org_id,
        kind=kind,
        title=f"Node '{display_name}' is online" if new_status == "online" else f"Node '{display_name}' went offline",
        body="CloudNode is connected and reporting." if new_status == "online" else "No heartbeat received in over 90 seconds.",
        severity="info" if new_status == "online" else "warning",
        audience="admin",
        link="/admin",
        node_id=node_id,
        db=db,
    )


# ── Read-state helpers ─────────────────────────────────────────────

def _get_or_init_state(
    db: Session, clerk_user_id: str, org_id: str
) -> UserNotificationState:
    """Return the user's read-state row, creating it on first access.

    First-time users see every existing notification as "unread" would be
    noisy, so we initialise last_viewed_at to NOW on creation — meaning a
    brand new user only sees notifications that arrive after they first
    load the app.
    """
    state = (
        db.query(UserNotificationState)
        .filter_by(clerk_user_id=clerk_user_id, org_id=org_id)
        .first()
    )
    if state is None:
        state = UserNotificationState(
            clerk_user_id=clerk_user_id,
            org_id=org_id,
            last_viewed_at=datetime.now(tz=UTC).replace(tzinfo=None),
        )
        db.add(state)
        db.commit()
        db.refresh(state)
    return state


def _audience_filter_clause(user: AuthUser):
    """SQLAlchemy filter that hides admin-only notifications from non-admins."""
    if user.is_admin:
        return None  # admins see everything
    return Notification.audience == "all"


# ── Routes ─────────────────────────────────────────────────────────

@router.get("")
async def list_notifications(
    limit: int = Query(default=50, le=200, ge=1),
    # OFFSET is O(n) — cap so no one can force SQLite to skip billions.
    offset: int = Query(default=0, ge=0, le=1_000_000),
    hours: int = Query(default=168, le=720),  # default 7 days, max 30 days
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Paginated inbox for the current user, newest first.

    Non-admins never see ``audience="admin"`` rows.  Read-state is
    reported per-item (based on last_viewed_at) so the UI can render
    the unread ones differently without another round trip.
    """
    since = datetime.now(tz=UTC).replace(tzinfo=None) - timedelta(hours=hours)

    # Initialise read-state first so we know the user's cleared_at
    # threshold before building the query.  Cleared notifications are
    # filtered out here (not hard-deleted) so other users in the same
    # org still see them and audit queries still see every row.
    state = _get_or_init_state(db, user.user_id, user.org_id)
    last_viewed = state.last_viewed_at
    cleared_at = state.cleared_at

    query = db.query(Notification).filter(
        Notification.org_id == user.org_id,
        Notification.created_at >= since,
    )
    if cleared_at is not None:
        query = query.filter(Notification.created_at > cleared_at)

    aud_clause = _audience_filter_clause(user)
    if aud_clause is not None:
        query = query.filter(aud_clause)

    total = query.count()
    rows = (
        query.order_by(Notification.created_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )

    items = []
    for n in rows:
        d = n.to_dict()
        d["unread"] = bool(last_viewed is None or (n.created_at and n.created_at > last_viewed))
        items.append(d)

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "last_viewed_at": last_viewed.isoformat() if last_viewed else None,
        "notifications": items,
    }


@router.get("/unread-count")
async def unread_count(
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Cheap count for the bell badge. Cap at 99 for display sanity."""
    state = _get_or_init_state(db, user.user_id, user.org_id)

    query = db.query(Notification).filter(
        Notification.org_id == user.org_id,
        Notification.created_at > state.last_viewed_at,
    )
    aud_clause = _audience_filter_clause(user)
    if aud_clause is not None:
        query = query.filter(aud_clause)

    count = query.count()
    return {
        "unread": count,
        "capped": count > 99,
        "last_viewed_at": state.last_viewed_at.isoformat() if state.last_viewed_at else None,
    }


@router.post("/mark-viewed")
async def mark_viewed(
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Bump the user's last_viewed_at to now, clearing the unread badge."""
    state = _get_or_init_state(db, user.user_id, user.org_id)
    state.last_viewed_at = datetime.now(tz=UTC).replace(tzinfo=None)
    db.commit()
    return {
        "success": True,
        "last_viewed_at": state.last_viewed_at.isoformat(),
    }


@router.post("/clear-all")
async def clear_all(
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Hide every currently-visible notification from this user's inbox.

    Stamps both ``cleared_at`` (list filter) and ``last_viewed_at``
    (unread count) to "now" so the panel becomes empty and the badge
    drops to zero in a single round trip.  Nothing is deleted —
    notifications remain in the DB for audit, incidents, and for
    other users in the same org who haven't cleared.  Anything
    created after this call reappears normally.
    """
    state = _get_or_init_state(db, user.user_id, user.org_id)
    now = datetime.now(tz=UTC).replace(tzinfo=None)
    state.cleared_at = now
    state.last_viewed_at = now
    db.commit()
    return {
        "success": True,
        "cleared_at": state.cleared_at.isoformat(),
        "last_viewed_at": state.last_viewed_at.isoformat(),
    }


@router.post("/request-admin-promotion")
@limiter.limit("3/hour")
async def request_admin_promotion(
    request: Request,
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Member-initiated request to be promoted to admin role.

    Fires a notification (inbox + email) to every admin in the org.
    Admins see who asked, with a deep-link to the Settings page where
    they can grant or deny via Clerk's standard role management.

    No-op for users who are ALREADY admins — returns a friendly 400
    rather than emitting a confusing "X requested admin access" notif
    to themselves.

    Rate-limited to 3 requests per hour per org bucket.  A member
    spamming admins doesn't get through; a member who clicked twice
    by accident doesn't either.  3/hour is generous enough that an
    admin requesting promotion (already admin → 400) plus a couple
    of legit member retries after Clerk role propagation lag won't
    trip the cap.
    """
    if user.is_admin:
        raise HTTPException(
            status_code=400,
            detail=(
                "You're already an admin in this organization — no "
                "need to request promotion."
            ),
        )

    requester = audit_label(user) or user.email or user.user_id or "a member"

    create_notification(
        org_id=user.org_id,
        kind="member_promotion_requested",
        title=f"{requester} requested admin access",
        body=(
            f"{requester} has requested to be promoted to admin in "
            f"your organization.  Review their access needs and, if "
            f"appropriate, promote them via Settings → Members.  This "
            f"is an in-app request — Clerk's role management is the "
            f"source of truth for who actually gets admin."
        ),
        severity="info",
        audience="admin",
        link="/settings",
        meta={
            "requester_user_id": user.user_id,
            "requester_email": user.email,
            "requester_label": requester,
        },
        db=db,
    )

    write_audit(
        db,
        org_id=user.org_id,
        event="member_promotion_requested",
        user_id=user.user_id,
        username=audit_label(user),
        details={"requester_label": requester},
        request=request,
    )

    return {
        "success": True,
        "message": (
            "Your request has been sent to your organization's admins. "
            "They'll be notified by email and in their dashboard."
        ),
    }


@router.get("/stream")
@limiter.limit("60/minute")
async def stream_notifications(
    request: Request,
    user: AuthUser = Depends(require_view),
):
    """SSE — streams new notifications to the bell panel in real time.

    The audience filter is applied at broadcast time (see
    NotificationBroadcaster.notify) so non-admins never even receive
    admin-only events on the wire.

    Rate-limited to 60 connect attempts per minute per org.  The
    per-org subscriber cap (``broadcaster.subscribe``) prevents
    accumulation, but without a connect-rate cap a hostile client
    could rapidly churn open→cap-hit→reject and burn JWT-verify CPU
    on every cycle.  60/min is well above legitimate usage (browser
    tabs reconnect on the order of seconds-to-minutes, not multiple
    times per second) and the same cap as the audit-logs endpoint.
    """
    from app.core.plans import get_plan_limits
    org_id = user.org_id
    is_admin = user.is_admin
    cap = get_plan_limits(user.plan).get("max_sse_subscribers", MAX_SSE_SUBSCRIBERS_PER_ORG)
    queue = notification_broadcaster.subscribe(org_id, is_admin, cap)
    if queue is None:
        raise HTTPException(
            status_code=429,
            detail=(
                f"Too many open notification streams for this org (cap: "
                f"{cap} on your current plan). Close unused tabs and retry, "
                f"or upgrade for a higher cap."
            ),
        )

    async def event_generator():
        try:
            yield f"data: {json.dumps({'type': 'connected', 'org_id': org_id})}\n\n"
            while True:
                try:
                    event = await asyncio.wait_for(queue.get(), timeout=25.0)
                    yield f"data: {json.dumps(event)}\n\n"
                except TimeoutError:
                    yield ": keepalive\n\n"
        except asyncio.CancelledError:
            pass
        finally:
            notification_broadcaster.unsubscribe(org_id, queue)

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


# ── Email preferences ──────────────────────────────────────────────
# Per-org per-kind toggles for the email side-channel.  GET is
# require_view (anyone in the org can SEE current prefs); POST is
# require_admin + audit (only admins can change them).
#
# The shape returned matches the keys in _EMAIL_KIND_TO_SETTING — a
# stable contract for the frontend toggle UI.  Adding a new kind
# means: add to _EMAIL_KIND_TO_SETTING, add a template, add a
# checkbox to the frontend.  No API change.


class EmailPreferences(BaseModel):
    """Request body for POST /email/preferences.

    Each field is optional — clients only send the toggles they're
    actually changing.  Unset fields keep their existing values.

    Note that some setting keys gate multiple notification kinds
    (``email_camera_offline`` controls both ``camera_offline`` and
    ``camera_online`` emails; ``email_mcp_key_audit`` controls both
    create and revoke).  See ``_EMAIL_KIND_TO_SETTING`` for the
    full mapping.  The UI shows one toggle per setting key.
    """
    email_camera_offline: Optional[bool] = None
    email_node_offline: Optional[bool] = None
    email_incident_created: Optional[bool] = None
    email_mcp_key_audit: Optional[bool] = None
    email_cloudnode_disk_low: Optional[bool] = None
    email_member_audit: Optional[bool] = None
    email_motion: Optional[bool] = None


def _current_email_prefs(db: Session, org_id: str) -> dict:
    """Return the org's effective email prefs as a {key: bool} dict.

    Reads each setting; falls back to the per-kind default in
    ``_EMAIL_KIND_TO_SETTING`` when the row is absent.  This is
    what the frontend toggle UI shows on first load — the absence
    of a Setting row is presented as the default ON state, not a
    blank "unset" state.
    """
    out = {}
    for _kind, (key, default) in _EMAIL_KIND_TO_SETTING.items():
        val = Setting.get(db, org_id, key, None)
        if val is None:
            out[key] = default
        else:
            out[key] = (val == "true")
    return out


@router.get("/email/preferences")
async def get_email_preferences(
    user: AuthUser = Depends(require_view),
    db: Session = Depends(get_db),
):
    """Return the current per-kind email toggles for the org.

    Includes ``email_globally_enabled`` flag derived from
    ``settings.EMAIL_ENABLED`` so the frontend can show "emails are
    currently turned off at the platform level" copy alongside
    individually-still-enabled toggles.  This is the difference
    between the operator's kill-switch and the org's prefs — the UI
    needs both signals to render the right state.
    """
    return {
        "email_globally_enabled": settings.EMAIL_ENABLED,
        "preferences": _current_email_prefs(db, user.org_id),
    }


@router.post("/email/preferences")
async def update_email_preferences(
    request: Request,
    prefs: EmailPreferences,
    user: AuthUser = Depends(require_admin),
    db: Session = Depends(get_db),
):
    """Update the org's per-kind email toggles.

    Only fields present in the request body are touched — partial
    updates are the norm (frontend toggles fire one at a time).
    Audit row written for every change so admin actions are
    traceable.

    Returns the updated full pref dict so the frontend doesn't need
    a follow-up GET to reflect the new state.
    """
    changes = []
    for key, value in prefs.model_dump(exclude_unset=True).items():
        if value is None:
            continue
        # Validate the key is one we recognise.  Pydantic already
        # restricts the field set, but defense in depth — if a
        # future field gets added without a corresponding
        # _EMAIL_KIND_TO_SETTING entry, this rejects it cleanly.
        if not any(cfg[0] == key for cfg in _EMAIL_KIND_TO_SETTING.values()):
            continue
        Setting.set(db, user.org_id, key, "true" if value else "false")
        changes.append(f"{key}={value}")

    if changes:
        write_audit(
            db,
            org_id=user.org_id,
            event="email_prefs_updated",
            user_id=user.user_id,
            username=user.email or user.username,
            details={"changes": changes},
            request=request,
        )

    return {
        "email_globally_enabled": settings.EMAIL_ENABLED,
        "preferences": _current_email_prefs(db, user.org_id),
        "changes": changes,
    }


# ── Unsubscribe ────────────────────────────────────────────────────
# Public endpoint, no auth required — the JWT in the URL is the
# auth.  Rate-limited via the global slowapi middleware (every route
# is bounded by ``tenant_aware_key`` + the default per-IP cap) so a
# stream of bad tokens can't burn the DB.
#
# Returns HTML (not JSON) because this is end-user facing — the
# user clicked a link in their email, they expect a web page, not
# a 200 OK with `{"status": "unsubscribed"}`.

_UNSUBSCRIBE_HTML_OK = """<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Unsubscribed</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 540px;
         margin: 80px auto; padding: 0 24px; color: #111; line-height: 1.5; }}
  h1 {{ font-size: 22px; margin: 0 0 12px; }}
  p {{ color: #555; }}
  .ok {{ color: #16a34a; font-weight: 600; }}
  a {{ color: #22c55e; }}
</style></head>
<body>
  <h1><span class="ok">✓</span> You're unsubscribed</h1>
  <p>This email address won't receive Sentinel notification emails
     anymore (you clicked unsubscribe on a <strong>{kind}</strong> alert).</p>
  <p>Other members of your organization are unaffected.  Org-wide email
     preferences can be fine-tuned any time in your
     <a href="{frontend}/settings#settings-notifications">notification settings</a>.</p>
</body></html>"""

_UNSUBSCRIBE_HTML_ERROR = """<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Link expired</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 540px;
         margin: 80px auto; padding: 0 24px; color: #111; line-height: 1.5; }}
  h1 {{ font-size: 22px; margin: 0 0 12px; }}
  p {{ color: #555; }}
  a {{ color: #22c55e; }}
</style></head>
<body>
  <h1>Link not recognised</h1>
  <p>This unsubscribe link looks invalid or has been superseded.
     Sign in to your <a href="{frontend}/settings#settings-notifications">
     notification settings</a> to manage email alerts directly.</p>
</body></html>"""


def _safe_html(s: str) -> str:
    """HTML-escape a string for embedding in the unsubscribe pages.

    The unsubscribe templates use ``str.format()`` (not Jinja2) so
    autoescape doesn't apply.  Anything we substitute that COULD
    contain user-controlled content needs explicit escaping.

    Realistically the values come from a verified JWT (``kind``) and
    server config (``frontend``), so neither is reachable by an
    attacker without already having the Clerk secret.  But escaping
    is one line and removes a future footgun.
    """
    import html as _html
    return _html.escape(s or "", quote=True)


@router.get("/email/unsubscribe", response_class=HTMLResponse)
@limiter.limit("60/minute")
async def email_unsubscribe(
    request: Request,
    t: str = Query(..., description="Signed unsubscribe token"),
    db: Session = Depends(get_db),
):
    """Process an unsubscribe link click.

    Verifies the JWT and suppresses the RECIPIENT ADDRESS it was issued
    to (an EmailSuppression row, which the send worker already checks
    before every send), then renders a confirmation page.

    Why per-address and not the org-wide toggle (the v1 behaviour):
    tokens live in inboxes forever-ish, including the inboxes of people
    since REMOVED from the org — flipping the org Setting let any past
    recipient permanently disable a whole org's security-alert emails.
    Suppressing the clicking address honours the actual promise of an
    unsubscribe link ("stop emailing ME") with no cross-member blast
    radius; org-wide kind toggles remain available to admins in
    Settings → Notifications.

    Rate-limited via slowapi.  This endpoint is PUBLIC (no auth —
    the JWT in the URL is the auth) so without an explicit limit,
    one leaked link could be hammered to write rows in a tight loop.
    60/min is well above any plausible legitimate use but rules out
    burst attacks.  The shared Limiter does NOT apply default
    limits, so explicit @limiter.limit is required here.
    """
    from app.models.models import EmailSuppression

    frontend = (settings.FRONTEND_URL or "").rstrip("/")
    frontend_safe = _safe_html(frontend)

    decoded = verify_token(t)
    if decoded is None:
        return HTMLResponse(
            _UNSUBSCRIBE_HTML_ERROR.format(frontend=frontend_safe),
            status_code=400,
        )

    org_id, kind, rcpt = decoded

    try:
        existing = (
            db.query(EmailSuppression)
            .filter(EmailSuppression.address == rcpt)
            .first()
        )
        if not existing:
            db.add(EmailSuppression(
                address=rcpt,
                reason="unsubscribe",
                source="unsubscribe_link",
            ))
            db.commit()
    except Exception:
        logger.exception("[Unsubscribe] failed to write suppression row")
        try:
            db.rollback()
        except Exception:
            pass
        # Don't surface the DB error to the user — they clicked an
        # unsubscribe link, they want to feel unsubscribed.  The
        # link is idempotent; they can click again or use the
        # settings page.

    # Audit (no user_id since this is a public link click).  Mask the
    # local part of the address — audit details shouldn't be an email
    # directory.
    try:
        local, _, domain = rcpt.partition("@")
        masked = f"{local[:1]}***@{domain}" if domain else "***"
        write_audit(
            db, org_id=org_id, event="email_unsubscribed",
            details={"kind": kind, "via_link": True, "address": masked},
        )
    except Exception:
        logger.exception("[Unsubscribe] audit write failed")

    # Pretty-print the kind for the user-facing copy.  "camera_offline"
    # → "camera offline" is friendlier than "email_camera_offline".
    pretty_kind = kind.replace("_", " ")
    return HTMLResponse(
        _UNSUBSCRIBE_HTML_OK.format(
            kind=_safe_html(pretty_kind), frontend=frontend_safe,
        ),
    )
